---
abstract: 'Simple DWIM Agile Tool'
author:
  - 'Aaron Trevena'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FlyHalf
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Realm::SimpleDB: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80032
  CatalystX::RoleApplicator: 0
  Config::General: 0
  DBIx::Class::DynamicDefault: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::InflateColumn::DateTime: 0
  DBIx::Class::InflateColumn::FS: 0
  DBIx::Class::TimeStamp: 0
  DateTime::Duration: 0
  File::Assets: 0
  File::Pid: 0
  HTML::FormHandler: 0
  HTML::FormHandler::Model::DBIC: 0
  HTML::FormHandlerX::Form::JQueryValidator: 0
  Method::Signatures::Simple: 0
  Moose: 0
  MooseX::NonMoose: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
