---
abstract: 'Simple DWIM Agile Tool'
author:
  - 'Aaron Trevena'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FlyHalf
no_index:
  directory:
    - inc
    - t
requires:
  Captcha::reCAPTCHA: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Realm::SimpleDB: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80032
  Catalyst::TraitFor::Request::BrowserDetect: 0
  Catalyst::View::Email: 0
  CatalystX::RoleApplicator: 0
  Config::General: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::InflateColumn::FS: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::TimeStamp: 0
  Email::Sender: 0.102360
  Email::Valid: 0
  File::Pid: 0
  HTML::Restrict: 0
  Method::Signatures::Simple: 0
  Moose: 0
  MooseX::NonMoose: 0
  Net::Domain::TLD: 0
  Text::CSV::Simple: 0
  XML::Feed: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
