package FlyHalf::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'FlyHalf::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dbname=flyhalf',
        user => 'flyhalfuser',
        password => 'scrumta4stic',
    }
);

=head1 NAME

FlyHalf::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<FlyHalf>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<FlyHalf::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.54

=head1 AUTHOR

Aaron Trevena

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
